name: Build & Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: build
      AWS_REGION: us-west-1
      S3_BUCKET: 3d-sefa
      DISTRIBUTION_ID: E2XWTFZCKFMWL3

    steps:
      # ───────────── repo + build ─────────────
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 18 }

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Upload entire site
        run: |
          aws s3 sync . "s3://$S3_BUCKET" --delete --no-progress \
            --exclude ".git/*" \
            --exclude "node_modules/*" \
            --exclude ".github/*"