name: Build & Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: build
      AWS_REGION: us-west-1
      S3_BUCKET: 3d-sefa
      DISTRIBUTION_ID: E2XWTFZCKFMWL3

    steps:
      # ───────────── repo + build ─────────────
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 18 }

      - run: npm ci
      - name: Run build
        run: npm run build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Upload site
        run: aws s3 sync build/ "s3://${{ env.S3_BUCKET }}" --delete --no-progress

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRIBUTION_ID }} \
            --paths "/*"