name: Build & Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: build
      AWS_REGION: us-west-1
      S3_BUCKET: 3d-sefa
      DISTRIBUTION_ID: E2XWTFZCKFMWL3

    steps:
      # ───────────── repo + build ─────────────
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 18 }

      - run: npm ci
      - name: Run build
        run: npm run build

      - name: Ensure Potree viewer is in build
        run: |
          if [ ! -f "$BUILD_DIR/potree/potree.js" ]; then
            echo "→ potree viewer missing – copying"
            cp -R potree "$BUILD_DIR"/
          else
            echo "✓ potree viewer already present – nothing to copy"
          fi

      # ───────────── AWS creds ─────────────
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      # ───────────── uploads ─────────────
      - name: Upload build artefacts
        run: aws s3 sync "$BUILD_DIR" "s3://$S3_BUCKET" --delete --no-progress

      - name: Upload libs
        run: |
          if [ -d libs ]; then
            aws s3 sync libs "s3://$S3_BUCKET/libs" --delete --no-progress
          fi

      - name: Upload models
        run: |
          if [ -d models ]; then
            aws s3 sync models "s3://$S3_BUCKET/models" --delete --no-progress
          fi

      - name: Upload resources (shaders, textures, etc.)
        run: |
          if [ -d resources ]; then
            aws s3 sync resources "s3://$S3_BUCKET/resources" --delete --no-progress
          fi

      - name: Upload thumbnails
        run: |
          if [ -d thumbnails ]; then
            aws s3 sync thumbnails "s3://$S3_BUCKET/thumbnails" --delete --no-progress
          fi

      # ───────────── CloudFront ─────────────
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$DISTRIBUTION_ID" \
            --paths "/*"