name: Build & Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: build
      BUILD_CMD: npm run build

      AWS_REGION: us-west-1
      S3_BUCKET: 3d-sefa
      S3_PREFIX: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Run build
        run: $BUILD_CMD

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}
      - name: Upload to S3
        run: |
          aws s3 sync "$BUILD_DIR" "s3://$S3_BUCKET/$S3_PREFIX" \
            --delete --acl public-read
