name: Build & Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: build
      MODELS_DIR: models
      BUILD_CMD: npm run build
      DISTRIBUTION_ID: E2XWTFZCKFMWL3

      AWS_REGION: us-west-1
      S3_BUCKET: 3d-sefa
      S3_PREFIX: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Run build
        run: $BUILD_CMD

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Upload build artefacts
        run: |
          aws s3 sync build  "s3://$S3_BUCKET"        --delete --no-progress
      - name: Upload libs
        run: |
          if [ -d libs ]; then
            aws s3 sync libs "s3://$S3_BUCKET/libs"   --delete --no-progress
          fi
      - name: Upload models
        run: |
          if [ -d models ]; then
            aws s3 sync models "s3://$S3_BUCKET/models" --delete --no-progress
          fi
      - name: Upload resources (shaders, textures, etc.)
        run: |
          if [ -d resources ]; then
            aws s3 sync resources "s3://$S3_BUCKET/resources" --delete --no-progress
          fi

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$DISTRIBUTION_ID" \
            --paths "/*"